name: Autoconf CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --with-tests
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
