name: configure CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: generate configure script
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-tests
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
